DROP TABLE IF EXISTS Actions;
DROP TABLE IF EXISTS Actuators;
DROP TABLE IF EXISTS Measures;
DROP TABLE IF EXISTS Sensors;

DROP TABLE IF EXISTS GreenHousePlants;
DROP TABLE IF EXISTS GreenHouses;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Plants;